---
- src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.13"
  name: clickhouse

- src: git@github.com:Saint-Pablo-3/vector-role.git
  scm: git
  version: "main"
  name: vector

- src: git@github.com:Saint-Pablo-3/lighthouse-role.git
  scm: git
  version: "main"
  name: lighthouse
